# Generated by Django 5.2.8 on 2025-11-10 00:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Краткое описание')),
                ('image_cat', models.ImageField(blank=True, upload_to='category/', verbose_name='Изображение категории')),
                ('slug', models.SlugField(blank=True, max_length=100, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_h', models.CharField(max_length=50, unique=True, verbose_name='Имя')),
                ('image', models.ImageField(upload_to='human/', verbose_name='Фотография')),
                ('descriptions', models.TextField(verbose_name='Описание')),
                ('slug', models.SlugField(blank=True, max_length=100, verbose_name='URL')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='humans', to='women.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Человек',
                'verbose_name_plural': 'Люди',
                'ordering': ['-created_at'],
            },
        ),
    ]
